In [1]:
import torch

In [2]:
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [3]:
x.requires_grad_(True) # x = torch.arange(4.0, requires_grad_=True)
x.grad

tensor([ 0.,  4.,  8., 12.])

In [4]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [5]:
# 默认一个计算图只能调用一次.backward(), 如果需要多次调用可以添加参数retain_graph=True
# 多次调用会导致x.grad的值不一样？？？
y.backward(retain_graph=True)
x.grad

tensor([ 0.,  4.,  8., 12.])

In [8]:
x.grad == 4 * x

tensor([True, True, True, True])

In [23]:
x.grad.zero_()
y = x * x
x, y, y.sum()

(tensor([0., 1., 2., 3.], requires_grad=True),
 tensor([0., 1., 4., 9.], grad_fn=<MulBackward0>),
 tensor(14., grad_fn=<SumBackward0>))

In [24]:
y.sum().backward()

In [26]:
x.grad == 2*x

tensor([True, True, True, True])

In [31]:
x.grad.zero_()
y = x * x
u = y.detach() # 把y当成一个常数，而不是x的函数，u 不再与 x 有梯度关系
y, u

(tensor([0., 1., 4., 9.], grad_fn=<MulBackward0>), tensor([0., 1., 4., 9.]))

In [29]:
z = u * x
z

tensor([ 0.,  1.,  8., 27.], grad_fn=<MulBackward0>)

In [30]:
z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [14]:
x.grad.zero_()
y.sum().backward()
x.grad == 2*x

tensor([True, True, True, True])

In [16]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

a = torch.randn(size=(), requires_grad=True)
d = f(a)
d.backward()

a.grad == d/a

tensor(True)