In [2]:
import torch
from torch import nn

torch.device('cpu'), torch.cuda.device('cuda'), torch.cuda.device('cuda:1')

(device(type='cpu'),
 <torch.cuda.device at 0x7f5738ff3bb0>)

In [3]:
torch.cuda.device_count()

1

In [5]:
def try_gpu(i=0):
    if torch.cuda.device_count() >= i + 1:
        return torch.device(f'cuda:{i}')
    return torch.device('cpu')

try_gpu()

device(type='cuda', index=0)

In [8]:
x = torch.tensor([1, 2, 3])
x.device

device(type='cpu')

In [13]:
X = torch.ones(2, 3, device=try_gpu())
X.device

device(type='cuda', index=0)

In [21]:
Y = torch.ones(2, 3)
Y.device

device(type='cpu')

In [17]:
Z = X.cuda(0)
print(X)
print(Z)

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')
tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')


In [23]:
Z + X

tensor([[2., 2., 2.],
        [2., 2., 2.]], device='cuda:0')

In [24]:
Y + X

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

In [28]:
net = nn.Sequential(nn.Linear(3, 1))
net = net.to(device=try_gpu())

net

Sequential(
  (0): Linear(in_features=3, out_features=1, bias=True)
)

In [30]:
net[0].weight.data.device

device(type='cuda', index=0)

In [32]:
!nvidia-smi

Tue May 20 23:55:53 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 570.144                Driver Version: 570.144        CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4060 ...    Off |   00000000:01:00.0  On |                  N/A |
| N/A   43C    P5              9W /   60W |     568MiB /   8188MiB |     19%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----